python -m app.vjepa_droid.extract_frame_embeddings \
    --videos_root /tmp2/hubertchang/p-jepa/data/droid/droid_repo/videos/chunk-000 \
    --output_h5 /tmp2/hubertchang/p-jepa/data/droid/droid_frame_embeddings.h5 \
    --vjepa_checkpoint /tmp2/hubertchang/p-jepa/models/vitg-384.pt \
    --device cuda:0 \
    --batch_size 1 \
    --num_workers 4 \
    --crop_size 256 \
    --patch_size 16 \
    --max_num_frames 512 \
    --tubelet_size 1 \